baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Hambledon Village Shop"
googleAnalytics = "UA-67221322-8"
[params]
  googlefonts = "//fonts.googleapis.com/css?family=Asul|Chivo|Cardo|Pathway+Gothic+One|Rubik|Roboto+Mono|Tenor|Archivo+Black|Eczar|Work+Sans|Merriweather|Fira+Mono|Droid+Sans|Nunito+Sans:400,700"
[blackfriday]
  extensions = ["hardLineBreak"]